### ISSUE TITLE
Please update 19.1 branch tools/gnatcov/README.md info about binutils version

### ISSUE THREAD

**Issue by okellogg** [AdaCore/gnatcoverage#12]
Hi,

The 19.1 branch in [tools/gnatcov/README.md](https://github.com/AdaCore/gnatcoverage/tree/19.1/tools/gnatcov/README.md) section [Build from sources](https://github.com/AdaCore/gnatcoverage/blob/19.1/tools/gnatcov/README.md#build-from-sources---quick-example-for-an-intel-linux-host) point **2.** says

> Best is to use a Binutils release for this, at least 2.29 which is known to work.
>
> binutils-2.29 $ ./configure --enable-targets=all \\
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; --disable-werror --without-zlib --disable-gdb \\
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; --disable-sim --disable-ld --disable-libquadmath \\
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; --disable-readline
> binutils-2.29 $ make

However, the branch contains the commit [0bce932](https://github.com/AdaCore/gnatcoverage/commit/0bce9324f56a29833627ac776b532cad7b2ece6e),
```
commit 0bce9324f56a29833627ac776b532cad7b2ece6e
Author: Pierre-Marie de Rodat <derodat@adacore.com>
Date:   Wed May 31 18:33:22 2017 +0200

    libopcodes_bind: update to build with latest binutils
    
    Change-Id: I3f83ce8ead8210fb2aa4faf08be450b7e9f24ff4
    TN: Q529-032

M       tools/gnatcov/libopcodes_bind/dis_wrapper.c
```
which means that the binutils version should be at least 2.31.

HTH,
 Oliver

**Comment by okellogg** [comment]
This turned out to be a misconfiguration on our part. The build works with binutils-2.29 as well. Sorry for the noise.

**Comment by hainque** [comment]
Hello Olivier

> This turned out to be a misconfiguration on our part. The build works with binutils-2.29 as well. Sorry for the noise.

No pb, thanks for letting us know.

Cheers,

Olivier (as well)
