### ISSUE TITLE
Can't compile with gnat-gpl-2017 or continuous release "GNAT Pro Ada 19 20180415"

### ISSUE THREAD

**Issue by touisteur** [AdaCore/gnatcoverage#3]
Hi,

I can't find a way to compile the latest github version of gnatcoverage, the makefile stops with:

```
[touisteur@touisteur gnatcov]$ BINUTILS_SRC_DIR=/home/touisteur/gnat/gnatpro-19.0w-20180415-x86_64-linux/bin make
gprbuild -Pgnatcov -p -j0 \
	-XARCH=64 -XBUILD_MODE=dev \
	-XBINUTILS_SRC_DIR="/home/touisteur/gnat/gnatpro-19.0w-20180415-x86_64-linux/bin" \
	-XBINUTILS_BUILD_DIR="/home/touisteur/gnat/gnatpro-19.0w-20180415-x86_64-linux/bin" \
	gnatcov 
Compile
   [Ada]          gnatcov.adb
sc_obligations.ads:486:11: "Pragma_Max_Entry_Queue_Depth" is undefined
gprbuild: *** compilation phase failed
make: *** [obj64/gnatcov] Erreur 4
```

I know it's not an official version, I was just taking the latest of the bleeding edge available to me :-). I *did* try GNAT GPL 2017 and I saw even more problems (pragma Ada 2020...).

The build docs say a "recent" version of GNAT, but the latest available (to me) doesn't seem to work. Which version should I use (supposing I get access to PRO versions). 18.x ?

Any idea ?

Thanks in advance for your help.
BR
Lionel

**Comment by pmderodat** [comment]
Hello @touisteur,

This specific part of GNATcoverage is tightly coupled with the list of pragmas in GNAT. Although this list does not change very often, it changed recently in GNAT’s development branch, and thus currently the master branch cannot build with any GPL or FSF release of GNAT.

Given that you want to build specifically the master branch, two ways out come to my mind: either wait enough days to build your own FSF compiler once the corresponding GNAT patch is ported there, either remove the offending line in `sc_obligations.ads`. I hope this helps. :-)

**Comment by touisteur** [comment]
Hi @pmderodat,

thanks for your quick answer. I did try removing the offending line in sc_obligations.ads and it worked.

Thanks a lot.

Best regards.
Lionel

**Comment by pmderodat** [comment]
You are very welcome! :-)
