### ISSUE TITLE
Coverage annotations not working on executable compiled by GCC installed from apt

### ISSUE THREAD

**Issue by Reeeemi** [AdaCore/gnatcoverage#4]
When using GNATcoverage on a executable compiled by GCC on Ubuntu (installed from `apt`), every assembly instruction gets marked with a "-", indicating it was not executed. However, the program works fine, so I'm pretty sure some of the instructions do get executed ;-)

GNATCoverage output:

`gnatcov coverage --annotate=asm --level=insn a.out.trace`
```
000000000000063a -:  55               push   %rbp
000000000000063b -:  48 89 e5         mov    %rsp,%rbp
000000000000063e -:  48 8d 3d 9f 00 00 00   lea    0x9f(%rip),%rdi        # 0x6e4
0000000000000645 -:  e8 c6 fe ff ff   callq  0x510
000000000000064a -:  b8 00 00 00 00   mov    $0x0,%eax
000000000000064f -:  5d               pop    %rbp
0000000000000650 -:  c3               retq
```

This can be reproduced by compiling a Hello World program, for example using `gcc-7` on Ubuntu (`apt install gcc-7`).

When compiling the same program using `clang` or `icc`, the coverage annotations work fine. Interestingly, when using `gcc` provided with the GNAT Community Edition, coverage annotations also work fine. Hence, I suspect that the problem is with the `gcc` versions provided by `apt` specifically.

I hope I provided all information needed to investigate this.

Regards,

Remi

**Comment by pmderodat** [comment]
Hello @Reeeemi ,

By default, Ubuntu’s GCC uses the `-pie` option, which creates programs that are loaded just like dynamic libraries:
```
$ gcc foo.c
$ file a.out
a.out: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, […]
```
(see `pie executable` above, and https://stackoverflow.com/questions/34519521/gcc-creates-a-shared-object-instead-of-an-executable-binary for more details)

As of today, GNATcoverage does not support shared libraries (this is a known limitation), so it will not manage to compute the coverage of PIE programs. You can work around this passing the `-no-pie` compile option:
```
$ gcc -no-pie foo.c
$ file a.out
a.out: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, […]
```
