### ISSUE TITLE
Please update tools/gnatcov/README.md "Build from sources" for libadalang

### ISSUE THREAD

**Issue by okellogg** [AdaCore/gnatcoverage#5]
My first build attempt failed as follows:
```
make bin adapters VALGRIND_PREFIX=/usr BINUTILS_SRC_DIR=$HOME/tools/binutils-2.31
gprbuild -Pgnatcov -p -j0 \
-XARCH=64 -XBUILD_MODE=dev \
-XBINUTILS_SRC_DIR="/home/akellol/tools/binutils-2.31" \
-XBINUTILS_BUILD_DIR="/home/akellol/tools/binutils-2.31" \
gnatcov 
gnatcov.gpr:1:31: unknown project file: "libadalang"
gprbuild: "gnatcov" processing failed
make: *** [obj64/gnatcov] Error 4
```

Could you mention the dependency to [libadalang](https://github.com/AdaCore/libadalang) in the section [Build from sources](https://github.com/AdaCore/gnatcoverage/blob/master/tools/gnatcov/README.md#build-from-sources---quick-example-for-an-intel-linux-host)?
Thanks.

**Comment by pmderodat** [comment]
Hello @okellogg 

That’s a very good point: thank you for reporting this missing item in our README. We are going to enhance it.

**Comment by pmderodat** [comment]
This is now done. Thanks again!
